branches:
  only:
  - master

env:
  global:
  - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages

warnings_are_errors: true
r_build_args: '--no-manual'
r_check_args: '--no-build-vignettes --no-manual'

r:
  - release
  - devel

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - devtools
  - covr

r_github_packages:
  - r-lib/sessioninfo
  - Rdatatable/data.table
  - jimhester/covr
  - osofr/simcausal
  - osofr/condensier
  - tlverse/origami
  - tlverse/hal9001

after_success:
  ## coverage
  - travis_wait 30 Rscript -e "covr::codecov()"

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change

